## Full name: 
## R#: 
## HEX: 
## Title of the notebook
## Date: 

# Introduction to NumPy

## What is NumPy

(Quoting directly from https://numpy.org/doc/stable/user/whatisnumpy.html)

"NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

## Why is NumPy Fast?

Vectorization describes the absence of any explicit looping, indexing, etc., in the code - these things are taking place, of course, just “behind the scenes” in optimized, pre-compiled C code. Vectorized code has many advantages, among which are:

- vectorized code is more concise and easier to read

-    fewer lines of code generally means fewer bugs

-    the code more closely resembles standard mathematical notation (making it easier, typically, to correctly code mathematical constructs)

-    vectorization results in more “Pythonic” code. Without vectorization, our code would be littered with inefficient and difficult to read for loops.

Broadcasting is the term used to describe the implicit element-by-element behavior of operations; generally speaking, in NumPy all operations, not just arithmetic operations, but logical, bit-wise, functional, etc., behave in this implicit element-by-element fashion, i.e., they broadcast. Moreover, in the example above, a and b could be multidimensional arrays of the same shape, or a scalar and an array, or even two arrays of with different shapes, provided that the smaller array is “expandable” to the shape of the larger in such a way that the resulting broadcast is unambiguous. For detailed “rules” of broadcasting see numpy.doc.broadcasting.

## Who Else Uses NumPy?

NumPy fully supports an object-oriented approach, starting, once again, with ndarray. For example, ndarray is a class, possessing numerous methods and attributes. Many of its methods are mirrored by functions in the outer-most NumPy namespace, allowing the programmer to code in whichever paradigm they prefer. This flexibility has allowed the NumPy array dialect and NumPy ndarray class to become the de-facto language of multi-dimensional data interchange used in Python. "

## What does this mean for this course?

Numpy provides a more compact way to manage array arithmetic, and some other relevant operations.


## Arrays
A list is a collection of data that are somehow related. It is a convenient way to refer to a
collection of similar things by a single name, and using an index (like a subscript in math)
to identify a particular item.
Consider the variable ``x`` :
    [$x_0 = 7$,
    $x_1 = 11$,
    $x_2 = 5$,
    $x_3 = 9$,
    $x_4 = 13$,
    $\dots$,
    $x_N = 223$]
    
The variable name is ``x`` and the subscripts correspond to different values. Thus the value of
the variable named ``x`` associated with subscript 3 is the number 9.

An array in numpy is fundamentally a list, but with special methods conferred by the numpy subsystem.

### Example- 1D Arrays
__Let's create a 1D array from the 2000s (2000-2009):__ 

In [7]:
import numpy as np             #First, we need to import "numpy"
mylist = [2000,2001,2002,2003,2004,2005,2006,2007,2008,2009]         #Create a list of the years
print(mylist)                 #Check how it looks
np.array(mylist)              #Define it as a numpy array


[2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009]


array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009])

### Example- n-Dimensional Arrays
__Let's create a 5x2 array from the 2000s (2000-2009):__ 

In [8]:
myotherlist = [[2000,2001],[2002,2003],[2004,2005],[2006,2007],[2008,2009]]     #Since I want a 5x2 array, I should group the years two by two
print(myotherlist)             #See how it looks as a list
np.array(myotherlist)          #See how it looks as a numpy array

[[2000, 2001], [2002, 2003], [2004, 2005], [2006, 2007], [2008, 2009]]


array([[2000, 2001],
       [2002, 2003],
       [2004, 2005],
       [2006, 2007],
       [2008, 2009]])

### Exercise 1
__Using the numbers below:__
#### 9,18,333,22,25,120,7,43,50,3,7,94,953,57,11,154

__A) Create a 1D array__<br>
__B) Create a 4x4 array so that:__
- all numbers in the first row are single digits
- all numbers in the second row are two digit and even numbers
- all numbers in the third row are two digit and odd numbers
- all numbers in the fourth row are three digit numbers


In [9]:
import numpy as np
list1D = [9,18,333,22,25,120,7,43,50,3,7,94,953,57,11,154] 
print(np.array(list1D))
list4x4 = [[9,7,3,7],[18,22,50,94],[25,43,57,11],[333,120,953,154]]
print(np.array(list4x4))


[  9  18 333  22  25 120   7  43  50   3   7  94 953  57  11 154]
[[  9   7   3   7]
 [ 18  22  50  94]
 [ 25  43  57  11]
 [333 120 953 154]]


### Array (grid) arithmetic

You can perform arithmetic operations on arrays. 
For example, if you add the arrays, the arithmetic operator will work element-wise. 
The output will be an array of the same dimension.  
The arrays must have same dimension and length, otherwise it will generate an exception.

You can run an arithmetic operation on an array with a scalar value. 
The operation is applied to each element of the array.

### Example- 1D Array Arithmetic
- Define a 1D array with [0,12,24,36,48,60,72,84,96]
- Multiple all elements by 2
- Take all elements to the power of 2
- Find the maximum value of the array and its position
- Find the minimum value of the array and its position
- Define another 1D array with [-12,0,12,24,36,48,60,72,84]
- Find the summation and subtraction of these two arrays
- Find the multiplication of these two arrays

In [29]:
import numpy as np         #import numpy
Array1 = np.array([0,12,24,36,48,60,72,84,96])     #Step1: Define Array1
print(Array1)
print(Array1*2)     #Step2: Multiple all elements by 2
print(Array1**2)     #Step3: Take all elements to the power of 2
print(np.power(Array1,2)) #Another way to do the same thing, by using a function in numpy
print(np.max(Array1))     #Step4: Find the maximum value of the array
print(np.argmax(Array1))     ##Step4: Find the postition of the maximum value 
print(np.min(Array1))     #Step5: Find the minimum value of the array
print(np.argmin(Array1))     ##Step5: Find the postition of the minimum value 
Array2 = np.array([-12,0,12,24,36,48,60,72,84])     #Step6: Define Array2
print(Array2)
print(Array1+Array2)         #Step7: Find the summation of these two arrays
print(Array1-Array2)         #Step7: Find the subtraction of these two arrays
print(Array1*Array2)         #Step8: Find the multiplication of these two arrays


[ 0 12 24 36 48 60 72 84 96]
[  0  24  48  72  96 120 144 168 192]
[   0  144  576 1296 2304 3600 5184 7056 9216]
[   0  144  576 1296 2304 3600 5184 7056 9216]
96
8
0
0
[-12   0  12  24  36  48  60  72  84]
[-12  12  36  60  84 108 132 156 180]
[12 12 12 12 12 12 12 12 12]
[   0    0  288  864 1728 2880 4320 6048 8064]


### Example- n-Dimensional Array Arithmetic
- Define a 2x2 array with [5,10,15,20]
- Define another 2x2 array with [3,6,9,12]
- Find the summation and subtraction of these two arrays
- Find the minimum number in the multiplication of these two arrays
- Find the position of the maximum in the multiplication of these two arrays
- Find the mean of the multiplication of these two arrays
- Find the mean of the first row of the multiplication of these two arrays


In [42]:
import numpy as np         #import numpy
Array1 = np.array([[5,10],[15,20]])     #Step1: Define Array1
print(Array1)
Array2 = np.array([[3,6],[9,12]])     #Step2: Define Array2
print(Array2)
print(Array1+Array2)     #Step3: Find the summation
print(Array1-Array2)     #Step3: Find the subtraction
MultArray = Array1@Array2         #Step4: To perform a typical matrix multiplication (or matrix product)
MultArray1 = Array1.dot(Array2)         #Step4: Another way To perform a  matrix multiplication
print(MultArray)
print(MultArray1)
print(np.min(MultArray))     #Step4: Find the minimum value of the multiplication
print(np.argmax(MultArray))     ##Step5: Find the postition of the maximum value 
print(np.mean(MultArray))     ##Step6: Find the mean of the multiplication of these two arrays 
print(np.mean(MultArray[0,:]))     ##Step7: Find the mean of the first row of the multiplication of these two arrays 


[[ 5 10]
 [15 20]]
[[ 3  6]
 [ 9 12]]
[[ 8 16]
 [24 32]]
[[2 4]
 [6 8]]
[[105 150]
 [225 330]]
[[105 150]
 [225 330]]
105
3
202.5
127.5


### Exercise 2
__Using the numbers below:__
#### 88,-5,9,22,46,2,-1,0

__A) Create a 2x4 array and print it out__<br>
__B) Add 6 to all elements, store it as a new object, and print it out__<br>
__C) Multiply all elements by 5, store it as a new object, and print it out__<br>
__D) Divide all elements by 7, store it as a new object, and print it out__<br>





In [41]:
import numpy as np         #import numpy
Array1 = np.array([[88,-5,9,22],[46,2,-1,0]])     #Step1: Define Array1
print(Array1)
Array2 = Array1+6     #Step2: Define Array2
print(Array2)
Array3 = Array2*5     #Step3: Define Array2
print(Array3)
Array4 = Array3/7     #Step3: Define Array2
print(Array4)


[[88 -5  9 22]
 [46  2 -1  0]]
[[94  1 15 28]
 [52  8  5  6]]
[[470   5  75 140]
 [260  40  25  30]]
[[67.14285714  0.71428571 10.71428571 20.        ]
 [37.14285714  5.71428571  3.57142857  4.28571429]]


## Matrix Operations

`save for future version -- demonstrate in class`

## Conditional Operations

You can use conditionals to find the values that match some criteria. 
The result of a conditional operation is also an array of booleans.

Rather than creating a separate array of booleans, you can specify the conditional operation directly on the argument array.

The syntax is a bit weird, so lets do some examples.

### Example- 1D Array Comparison
- Define a 1D array with [1.0,2.5,3.4,7,7]
- Define another 1D array with [5.0/5.0,5.0/2,6.8/2,21/3,14/2]
- Compare and see if the two arrays are equal
- Define another 1D array with [6,1.4,2.2,7.5,7]
- Compare and see if the first array is greater than or equal to the third array

In [1]:
import numpy as np         #import numpy
Array1 = np.array([1.0,2.5,3.4,7,7])     #Step1: Define Array1
print(Array1)
Array2 = np.array([5.0/5.0,5.0/2,6.8/2,21/3,14/2])     #Step2: Define Array1
print(Array2)
print(np.equal(Array1, Array2))             #Step3: Compare and see if the two arrays are equal
Array3 = np.array([6,1.4,2.2,7.5,7])     #Step4: Define Array3
print(Array3)
print(np.greater_equal(Array1, Array3))             #Step3: Compare and see if the two arrays are equal


[1.  2.5 3.4 7.  7. ]
[1.  2.5 3.4 7.  7. ]
[ True  True  True  True  True]
[6.  1.4 2.2 7.5 7. ]
[False  True  True False  True]


### Exercise 3- n-Dimensional Array Comparison
__Using the numbers below:__
#### 4,9,23,39,40,55,68,72

__A) Create a 2x2 array with all the even numbers and print it out__<br>
__B) Create a 2x2 array with all the odd numbers and print it out__<br>
__C) Compare the two arrays using the "less_equal" function from numpy package__

In [43]:
import numpy as np         #import numpy
Array1 = np.array([[4,40],[68,72]])     #Step1: Define Array1
print(Array1)
Array2 = np.array([[9,23],[39,55]])     #Step2: Define Array2
print(Array2)
print(np.less_equal(Array1,Array2))


[[ 4 40]
 [68 72]]
[[ 9 23]
 [39 55]]
[[ True False]
 [False False]]


# Copy vs. destroy and array

example

exercise

### Example- Copying and Deleting Arrays and Elements
- Define a 1D array, named "x" with [1,2,3]
- Define "y" so that "y=x"
- Define "z" as a copy of "x"
- Discuss the difference between y and z
- Delete the second element of x

In [7]:
import numpy as np         #import numpy
x = np.array([1,2,3])     #Step1: Define x
print(x)
y = x                     #Step2: Define y as y=x
print(y)
z = np.copy(x)            #Step3: Define z as a copy of x
print(z)
# For Step4: They look similar but check this out:
x[1] = 8                  # If we change x ...
print(x)
print(y)
print(z)
# By modifying x, y changes but z remains as a copy of the initial version of x.
x = np.delete(x, 1)      #Step5: Delete the second element of x
print(x)

[1 2 3]
[1 2 3]
[1 2 3]
[1 8 3]
[1 8 3]
[1 2 3]
[1 3]


### Exercise 4
__Using the numbers below:__
#### 1,2,3,4,5,6,7,8,9

__A) Create a 1D array and print it out__<br>
__B) Delete all the even numbers and print out the new version__<br>
__C) Make a copy of the array from step B and print it out__

In [2]:
import numpy as np         #import numpy
v = np.array([1,2,3,4,5,6,7,8,9])     #StepA: Define v
print(v)
vdel = np.delete(v, [1,3,5,7]) #StepB: Delete all the even numbers
print(vdel)
vcopy = np.copy(vdel)             #StepC: Make a copy of vdel
print(vcopy)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[1 3 5 7 9]


### Sorts

Python lists have a built-in `sort()` method that modifies the list in-place and a `sorted()` built-in function that builds a new sorted list from an iterable. So when sorting needs to be done, you should use the built-in tools. 

example

example

exercise

### Example- Sorting 1D Arrays
__Define a 1D array as ['FIFA 2020','Red Dead Redemption','Fallout','GTA','NBA 2018','Need For Speed'] and print it out. Then, sort the array alphabetically.__


In [10]:
import numpy as np         #import numpy
games = np.array(['FIFA 2020','Red Dead Redemption','Fallout','GTA','NBA 2018','Need For Speed'])
print(games)
print(np.sort(games))

['FIFA 2020' 'Red Dead Redemption' 'Fallout' 'GTA' 'NBA 2018'
 'Need For Speed']
['FIFA 2020' 'Fallout' 'GTA' 'NBA 2018' 'Need For Speed'
 'Red Dead Redemption']


### Example- Sorting n-Dimensional Arrays
__Define a 3x3 array with 17,-6,2,86,-12,0,0,23,12 and print it out. Then, sort the array.__

In [18]:
import numpy as np         #import numpy
a = np.array([[17,-6,2],[86,-12,0],[0,23,12]])
print(a)
print ("Along columns : \n", np.sort(a,axis = 0) ) #This will be sorting in each column
print ("Along rows : \n", np.sort(a,axis = 1) ) #This will be sorting in each row
print ("Sorting by default : \n", np.sort(a) )          #Same as above
print ("Along None Axis : \n", np.sort(a,axis = None) ) #This will be sorted like a 1D array


[[ 17  -6   2]
 [ 86 -12   0]
 [  0  23  12]]
Along columns : 
 [[  0 -12   0]
 [ 17  -6   2]
 [ 86  23  12]]
Along rows : 
 [[ -6   2  17]
 [-12   0  86]
 [  0  12  23]]
Sorting by default : 
 [[ -6   2  17]
 [-12   0  86]
 [  0  12  23]]
Along None Axis : 
 [-12  -6   0   0   2  12  17  23  86]


### Exercise 4
__A) Google: "Python how to Sort Numpy", find a good link with appropriate explanation, and add the link to your notebook__<br>
__Then, use the 4x4 array from Exercise 1, part2 and ...<br>
B) Print it out<br>
C) Sort it along the rows and print it out<br>
D) Sort it along the columns and print it out__<br>

In [44]:
# the link: https://www.programiz.com/python-programming/methods/list/sort

list4x4 = [[9,7,3,7],[18,22,50,94],[25,43,57,11],[333,120,953,154]]
print(np.array(list4x4)) #Step1
print ("Along rows : \n", np.sort(list4x4,axis = 1) ) #Step2
print ("Along columns : \n", np.sort(list4x4,axis = 0) ) #Step3

[[  9   7   3   7]
 [ 18  22  50  94]
 [ 25  43  57  11]
 [333 120 953 154]]
Along rows : 
 [[  3   7   7   9]
 [ 18  22  50  94]
 [ 11  25  43  57]
 [120 154 333 953]]
Along columns : 
 [[  9   7   3   7]
 [ 18  22  50  11]
 [ 25  43  57  94]
 [333 120 953 154]]


# Appending contents (vital)

## various array functions (sum,mean)

# Partitioning (Slice) Arrays

example

example

exercise

### Example- Slicing 1D Arrays
__Define a 1D array as [1,3,5,7,9], slice out the [3,5,7] and print it out.__

In [34]:
import numpy as np         #import numpy
a = np.array([1,3,5,7,9])     #Define the array
print(a)
aslice = a[1:4]             #slice the [3,5,7]
print(aslice)               #print it out


[1 3 5 7 9]
[3 5 7]


### Example- Slicing n-Dimensional Arrays
__Define a 5x5 array with "Superman, Batman, Jim Hammond, Captain America, Green Arrow, Aquaman, Wonder Woman, Martian Manhunter, Barry Allen, Hal Jordan, Hawkman, Ray Palmer, Spider Man, Thor, Hank Pym, Solar, Iron Man, Dr. Strange, Daredevil, Ted Kord, Captian Marvel, Black Panther, Wolverine, Booster Gold, Spawn " and print it out. Then:__
- Slice the first column and print it out
- Slice the third row and print it out
- Slice 'Wolverine' and print it out
- Slice a 3x3 array with 'Wonder Woman, Ray Palmer, Iron Man, Martian Manhunter, Spider Man, Dr. Strange, Barry Allen, Thor, Daredevil'

In [35]:
import numpy as np         #import numpy
Superheroes = np.array([['Superman', 'Batman', 'Jim Hammond', 'Captain America', 'Green Arrow'],
               ['Aquaman', 'Wonder Woman', 'Martian Manhunter', 'Barry Allen', 'Hal Jordan'],
               ['Hawkman', 'Ray Palmer', 'Spider Man', 'Thor', 'Hank Pym'],
               ['Solar', 'Iron Man', 'Dr. Strange', 'Daredevil', 'Ted Kord'],
               ['Captian Marvel', 'Black Panther', 'Wolverine', 'Booster Gold', 'Spawn']])
print(Superheroes) #Step1
print(Superheroes[:,0])
print(Superheroes[2,:])
print(Superheroes[4,2])
print(Superheroes[1:4,1:4])

[['Superman' 'Batman' 'Jim Hammond' 'Captain America' 'Green Arrow']
 ['Aquaman' 'Wonder Woman' 'Martian Manhunter' 'Barry Allen' 'Hal Jordan']
 ['Hawkman' 'Ray Palmer' 'Spider Man' 'Thor' 'Hank Pym']
 ['Solar' 'Iron Man' 'Dr. Strange' 'Daredevil' 'Ted Kord']
 ['Captian Marvel' 'Black Panther' 'Wolverine' 'Booster Gold' 'Spawn']]
['Superman' 'Aquaman' 'Hawkman' 'Solar' 'Captian Marvel']
['Hawkman' 'Ray Palmer' 'Spider Man' 'Thor' 'Hank Pym']
Wolverine
[['Wonder Woman' 'Martian Manhunter' 'Barry Allen']
 ['Ray Palmer' 'Spider Man' 'Thor']
 ['Iron Man' 'Dr. Strange' 'Daredevil']]


### Exercise 5
__Using the names below:__

"Cartman, Kenny, Kyle, Stan, Butters, Wendy, Chef, Mr. Mackey, Randy, Sharon, Sheila, Towelie"

__A) Create a 3x4 array and print it out <br>
B) Sort the array alphabetically by column and print it out <br>
C) From the sorted array, slice out a 2x2 array with ('Cartman, Randy, Sharon, Wendy'), and print it out__ <br>

In [40]:
import numpy as np         #import numpy
names = np.array([['Cartman','Kenny','Kyle','Stan'],['Butters','Wendy','Chef','Mr. Mackey'],['Randy','Sharon','Sheila','Towelie']])
print(names) #Step1
names_sorted = np.sort(names,axis = 0) 
print(names_sorted) #Step2
names_sliced = names_sorted[1:,0:2]
print(names_sliced) #Step3

[['Cartman' 'Kenny' 'Kyle' 'Stan']
 ['Butters' 'Wendy' 'Chef' 'Mr. Mackey']
 ['Randy' 'Sharon' 'Sheila' 'Towelie']]
[['Butters' 'Kenny' 'Chef' 'Mr. Mackey']
 ['Cartman' 'Sharon' 'Kyle' 'Stan']
 ['Randy' 'Wendy' 'Sheila' 'Towelie']]
[['Cartman' 'Sharon']
 ['Randy' 'Wendy']]
