# <font color=darkblue>Week 4 Assignment </font>

## Full name: 
## R#: 
## Title of the notebook:
## Date: 

![](https://miro.medium.com/max/1360/1*IRGHmiGsa16stedQvIaZfw.gif) <br>


___
### Question 1: A Southpark fan?

![](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/cb108017-ae2f-4f85-9f29-80ea8b3eaf36/d5gmaq0-903519b2-14c6-46e0-8e68-eb8a637e6397.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvY2IxMDgwMTctYWUyZi00Zjg1LTlmMjktODBlYThiM2VhZjM2XC9kNWdtYXEwLTkwMzUxOWIyLTE0YzYtNDZlMC04ZTY4LWViOGE2MzdlNjM5Ny5qcGcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.I4JKekrWGkqvJaRCRxiMwmDoJFtsXCOLAj7aiPEeUgs) <br>

__Using the names below:__

"Cartman, Kenny, Kyle, Stan, Butters, Wendy, Chef, Mr. Mackey, Randy, Sharon, Sheila, Towelie"

__A) Create a 3x4 array and print it out <br>
B) Sort the array alphabetically by column and print it out <br>
C) From the sorted array, slice out a 2x2 array with ('Cartman, Randy, Sharon, Wendy'), and print it out__ <br>

In [44]:
### import numpy
#import pandas

#mydata = pandas.DataFrame([content],[rows],[columns])
#mydata = numpy.array([content])

mydata = numpy.array([['Cartman','Kenny', 'Kyle', 'Stan'],
                      ['Butters', 'Wendy', 'Chef', 'Mr. Mackey'],
                      ['Randy', 'Sharon', 'Sheila', 'Towelie']])

print(mydata) #print the array
print('\n') # print a blank line
mydata[0]

[['Cartman' 'Kenny' 'Kyle' 'Stan']
 ['Butters' 'Wendy' 'Chef' 'Mr. Mackey']
 ['Randy' 'Sharon' 'Sheila' 'Towelie']]




array(['Cartman', 'Kenny', 'Kyle', 'Stan'], dtype='<U10')

In [46]:
print(numpy.sort(mydata,axis=1)) # sorting along a column (rows move)
print('\n') # print a blank line

[['Cartman' 'Kenny' 'Kyle' 'Stan']
 ['Butters' 'Chef' 'Mr. Mackey' 'Wendy']
 ['Randy' 'Sharon' 'Sheila' 'Towelie']]




In [47]:
print(numpy.sort(mydata,axis=0)) # sorting along a row (columns move)
print('\n') # print a blank line

[['Butters' 'Kenny' 'Chef' 'Mr. Mackey']
 ['Cartman' 'Sharon' 'Kyle' 'Stan']
 ['Randy' 'Wendy' 'Sheila' 'Towelie']]




In [49]:
slice2x2 = numpy.sort(mydata,axis=0)[1:3,0:2] # slice the array, put slice into new object
print(slice2x2)
print('\n') # print a blank line

sl2x2t = numpy.transpose(slice2x2) #transpose the object (linear algebra)
print(sl2x2t)
print('\n') # print a blank line

[['Cartman' 'Sharon']
 ['Randy' 'Wendy']]


[['Cartman' 'Randy']
 ['Sharon' 'Wendy']]




___
### Question2: A Numpy Playground

- Step1: Create a 2x5 array with [0,1,2,3,4,5,6,7,8,9] and name it "Array1"
- Step2: Extract all the odd numbers of "Array1" and store them in a new array: "Array2"
- Step3: In "Array1" replace 0,5, and 9 with 100,500, and 900.
- Step4: Add three other odd numbers to "Array2"
- Step5: Calculate the average of "Array2"
- Step6: Take "Array2" to the power of 5 and print the result. 

In [74]:
import numpy
array1 = numpy.array([[0,1,2,3,4],[5,6,7,8,9]])

print('My array 1 below:')
print(array1)
print('\n') # print a blank line

array2 = array1[array1 % 2 == 1]

print('My array 2 below:')
print(array2) # code modifed from https://stackoverflow.com/questions/61748834/extract-all-odd-numbers-from-numpy-array
print('\n') # print a blank line

copyofarray1 = array1

for i in range(0,2):
    for j in range(0,5):
        if(array1[i][j] == 0):
            array1[i][j]=100
        if(array1[i][j] == 5):
            array1[i][j]=500
        if(array1[i][j] == 9):
            array1[i][j]=900

print('My modified array 1 below:')
print(array1)
print('\n') # print a blank line

array2 = numpy.insert(array2,5,[11,13,21]) # adpated from example at https://www.geeksforgeeks.org/numpy-insert-python/

print('My modified array 2 below:')
print(array2)
print('\n') # print a blank line

print('average of array2 = ',numpy.average(array2))
print('\n') # print a blank line

print('array2 raised to popwer 5 = ',numpy.power(array2,5))
print('\n') # print a blank line


My array 1 below:
[[0 1 2 3 4]
 [5 6 7 8 9]]


My array 2 below:
[1 3 5 7 9]


My modified array 1 below:
[[100   1   2   3   4]
 [500   6   7   8 900]]


My modified array 2 below:
[ 1  3  5  7  9 11 13 21]


average of array2 =  8.75


array2 raised to popwer 5 =  [      1     243    3125   16807   59049  161051  371293 4084101]




___
### Question3: Bread and Butter! <br>

- Step1: Create a 1D (flatten) Numpy array of all the numbers in your R-number: R######## | It should have eight numbers
- Step2: Create another 1D array by multiplying the previous array by 2
- Step3: Create another 1D array by multiplying the first array by 5
- Step4: Create a Pandas Dataframe with the three previous arrays as its columns.
- Step5: Use appropriate functions from Pandas, describe the dataset, and explore the maximum, minimum and other specific characteristics of it.
- Step6: Reshape the dataframe into a 4x6 dataframe.


In [98]:
myrnumber = str(87656489)
myrlist = [int(i) for i in myrnumber]
myrlist
mRarray = numpy.array(myrlist)
mRarray
array22 = 2*mRarray #scalar multiply
array55 = 5*mRarray #scalar multiply
#mydata = pandas.DataFrame([content],[rows],[columns])
mydata = pandas.DataFrame()
mydata['flat R number']= mRarray
mydata['Double R']= array22
mydata['Five R']= array55
print(mydata)
print('\n') # print a blank line
print(mydata.describe())
print('\n') # print a blank line

   flat R number  Double R  Five R
0              8        16      40
1              7        14      35
2              6        12      30
3              5        10      25
4              6        12      30
5              4         8      20
6              8        16      40
7              9        18      45


       flat R number   Double R    Five R
count       8.000000   8.000000   8.00000
mean        6.625000  13.250000  33.12500
std         1.685018   3.370036   8.42509
min         4.000000   8.000000  20.00000
25%         5.750000  11.500000  28.75000
50%         6.500000  13.000000  32.50000
75%         8.000000  16.000000  40.00000
max         9.000000  18.000000  45.00000




![](https://freight.cargo.site/w/1200/i/c96b2ce17b2aee95c6e837552e3e38d058ac4ad2a6759448ed78128963790744/Happy_Coding_BC_6-03-05.png)