# <font color=darkblue>Week 4 Assignment </font>

## Full name: 
## R#: 
## Title of the notebook:
## Date: 

![](https://miro.medium.com/max/1360/1*IRGHmiGsa16stedQvIaZfw.gif) <br>


___
### Question 1: A Southpark fan?

![](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/cb108017-ae2f-4f85-9f29-80ea8b3eaf36/d5gmaq0-903519b2-14c6-46e0-8e68-eb8a637e6397.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvY2IxMDgwMTctYWUyZi00Zjg1LTlmMjktODBlYThiM2VhZjM2XC9kNWdtYXEwLTkwMzUxOWIyLTE0YzYtNDZlMC04ZTY4LWViOGE2MzdlNjM5Ny5qcGcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.I4JKekrWGkqvJaRCRxiMwmDoJFtsXCOLAj7aiPEeUgs) <br>

__Using the names below:__

"Cartman, Kenny, Kyle, Stan, Butters, Wendy, Chef, Mr. Mackey, Randy, Sharon, Sheila, Towelie"

__A) Create a 3x4 array and print it out <br>
B) Sort the array alphabetically by column and print it out <br>
C) From the sorted array, slice out a 2x2 array with ('Cartman, Randy, Sharon, Wendy'), and print it out__ <br>

In [40]:
import numpy as np         #import numpy
names = np.array([['Cartman','Kenny','Kyle','Stan'],['Butters','Wendy','Chef','Mr. Mackey'],['Randy','Sharon','Sheila','Towelie']])
print(names) #Step1
names_sorted = np.sort(names,axis = 0) 
print(names_sorted) #Step2
names_sliced = names_sorted[1:,0:2]
print(names_sliced) #Step3

[['Cartman' 'Kenny' 'Kyle' 'Stan']
 ['Butters' 'Wendy' 'Chef' 'Mr. Mackey']
 ['Randy' 'Sharon' 'Sheila' 'Towelie']]
[['Butters' 'Kenny' 'Chef' 'Mr. Mackey']
 ['Cartman' 'Sharon' 'Kyle' 'Stan']
 ['Randy' 'Wendy' 'Sheila' 'Towelie']]
[['Cartman' 'Sharon']
 ['Randy' 'Wendy']]


___
### Question2: A Numpy Playground

- Step1: Create a 2x5 array with [0,1,2,3,4,5,6,7,8,9] and name it "Array1"
- Step2: Extract all the odd numbers of "Array1" and store them in a new array: "Array2"
- Step3: In "Array1" replace 0,5, and 9 with 100,500, and 900.
- Step4: Add three other odd numbers to "Array2"
- Step5: Calculate the average of "Array2"
- Step6: Take "Array2" to the power of 5 and print the result. 

In [10]:
import numpy as np         #import numpy
# Step1:
Array1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(Array1)
# Step2:
Array2 = Array1[Array1%2 != 0]
print(Array2)
# Step3:
Array1[0] = 100
Array1[5] = 500
Array1[9] = 900
print(Array1)
# Step4:
Array2 = np.append(Array2,[11,13,15], axis=None)
print(Array2)
# Step5:
print(np.mean(Array2))
# Step6:
print(np.power(Array2,5))

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[100   1   2   3   4 500   6   7   8 900]
[ 1  3  5  7  9 11 13 15]
8.0
[     1    243   3125  16807  59049 161051 371293 759375]


___
### Question3: Bread and Butter! <br>

- Step1: Create a 1D (flatten) Numpy array of all the numbers in your R-number: R######## | It should have eight numbers
- Step2: Create another 1D array by multiplying the previous array by 2
- Step3: Create another 1D array by multiplying the first array by 5
- Step4: Create a Pandas Dataframe with the three previous arrays as its columns.
- Step5: Use appropriate functions from Pandas, describe the dataset, and explore the maximum, minimum and other specific characteristics of it.
- Step6: Reshape the dataframe into a 4x6 dataframe.


In [31]:
np.arange(4)

array([0, 1, 2, 3])

In [34]:
import numpy as np         #import numpy
import pandas as pd         #import pandas
#Step1:
A1 = np.array([2,4,5,6,5,4,3,3])
print(A1)
#Step2:
A2 = 2*A1
print(A2)
#Step3:
A3 = 5*A1
print(A3)
#Step4:
DF = pd.DataFrame(data=[A1, A2, A3]).T
DF.columns=["A1","A2","A3"]
print(DF)
#Step5:
print(DF.describe())
#Step6:
DFflat = DF.values.flatten()                 #Create a numpy array of the flatten DF
print(DFflat)
newDF = DFflat.reshape(4,6)                  #reshape the flatten array into a 4x6 array
print(newDF)
DF2 = pd.DataFrame(data=newDF, index=np.arange(4), columns=np.arange(6))          #create a 4x6 dataframe from the 4x6 array
print(DF2)

[2 4 5 6 5 4 3 3]
[ 4  8 10 12 10  8  6  6]
[10 20 25 30 25 20 15 15]
   A1  A2  A3
0   2   4  10
1   4   8  20
2   5  10  25
3   6  12  30
4   5  10  25
5   4   8  20
6   3   6  15
7   3   6  15
             A1         A2         A3
count  8.000000   8.000000   8.000000
mean   4.000000   8.000000  20.000000
std    1.309307   2.618615   6.546537
min    2.000000   4.000000  10.000000
25%    3.000000   6.000000  15.000000
50%    4.000000   8.000000  20.000000
75%    5.000000  10.000000  25.000000
max    6.000000  12.000000  30.000000
[ 2  4 10  4  8 20  5 10 25  6 12 30  5 10 25  4  8 20  3  6 15  3  6 15]
[[ 2  4 10  4  8 20]
 [ 5 10 25  6 12 30]
 [ 5 10 25  4  8 20]
 [ 3  6 15  3  6 15]]
   0   1   2  3   4   5
0  2   4  10  4   8  20
1  5  10  25  6  12  30
2  5  10  25  4   8  20
3  3   6  15  3   6  15


![](https://freight.cargo.site/w/1200/i/c96b2ce17b2aee95c6e837552e3e38d058ac4ad2a6759448ed78128963790744/Happy_Coding_BC_6-03-05.png)