In [1]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [2]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
import numpy as np

In [5]:
mtarray= np.array(mylist)

In [6]:
mtarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print(mtarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
len(mtarray)

3

In [10]:
mtarray = np.eye(3)

In [11]:
mtarray

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
print(np.sqrt(mtarray))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
