# <font color=darkred>Laboratory 7: Pandas for Butter! </font>

In [1]:
# Preamble script block to identify host, user, and kernel
import sys
! hostname
! whoami
print(sys.executable)
print(sys.version)
print(sys.version_info)

atomickitty.aws
engr1330content
/opt/conda/envs/python/bin/python
3.8.3 (default, Jul  2 2020, 16:21:59) 
[GCC 7.3.0]
sys.version_info(major=3, minor=8, micro=3, releaselevel='final', serial=0)


## Full name: 
## R#: 
## Title of the notebook:
## Date:
___

![](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pandas_logo.svg/1280px-Pandas_logo.svg.png) <br>

## <font color=purple>Pandas</font>
A data table is called a `DataFrame` in pandas (and other programming environments too).

The figure below from https://pandas.pydata.org/docs/getting_started/index.html illustrates a dataframe model:

![](https://pandas.pydata.org/docs/_images/01_table_dataframe.svg) 

Each column and each row in a dataframe is called a series, the header row, and index column are special.

To use pandas, we need to import the module, generally pandas has numpy as a dependency so it also must be imported



In [2]:
import numpy as np #Importing NumPy library as "np"
import pandas as pd #Importing Pandas library as "pd"

___
### <font color=darkgreen>Dataframe-structure using primative python</font>

First lets construct a dataframe like object using python primatives.
We will construct 3 lists, one for row names, one for column names, and one for the content.

In [3]:
mytabular = np.random.randint(1,100,(5,4))
myrowname = ['A','B','C','D','E']
mycolname = ['W','X','Y','Z']
mytable = [['' for jcol in range(len(mycolname)+1)] for irow in range(len(myrowname)+1)] #non-null destination matrix, note the implied loop construction

In [4]:
print(mytabular)

[[93 70 46 52]
 [ 8 76 68 72]
 [ 1 29 18 16]
 [66 96 96 57]
 [51 68 28 36]]


The above builds a placeholder named `mytable` for the psuedo-dataframe.
Next we populate the table, using a for loop to write the column names in the first row, row names in the first column, and the table fill for the rest of the table.

In [5]:
for irow in range(1,len(myrowname)+1): # write the row names
    mytable[irow][0]=myrowname[irow-1]
for jcol in range(1,len(mycolname)+1): # write the column names
    mytable[0][jcol]=mycolname[jcol-1]  
for irow in range(1,len(myrowname)+1): # fill the table (note the nested loop)
    for jcol in range(1,len(mycolname)+1):
        mytable[irow][jcol]=mytabular[irow-1][jcol-1]

Now lets print the table out by row and we see we have a very dataframe-like structure

In [6]:
for irow in range(0,len(myrowname)+1):
    print(mytable[irow][0:len(mycolname)+1])

['', 'W', 'X', 'Y', 'Z']
['A', 93, 70, 46, 52]
['B', 8, 76, 68, 72]
['C', 1, 29, 18, 16]
['D', 66, 96, 96, 57]
['E', 51, 68, 28, 36]


We can also query by row 

In [7]:
print(mytable[3][0:len(mycolname)+1])

['C', 1, 29, 18, 16]


Or by column

In [8]:
for irow in range(0,len(myrowname)+1):  #cannot use implied loop in a column slice
    print(mytable[irow][2])

X
70
76
29
96
68


Or by row+column index; sort of looks like a spreadsheet syntax.

In [9]:
print(' ',mytable[0][3])
print(mytable[3][0],mytable[3][3])

  Y
C 18


___
### <font color=darkgreen>Create a proper dataframe</font>
We will now do the same using pandas

In [10]:
df = pd.DataFrame(np.random.randint(1,100,(5,4)), ['A','B','C','D','E'], ['W','X','Y','Z'])
df

W   X   Y   Z
A  18  36  59  93
B  98  23  69  57
C  11  29  28   7
D  85  79  64  90
E  29  24  69  20

We can also turn our table into a dataframe, notice how the constructor adds header row and index column

In [11]:
df1 = pd.DataFrame(mytable)
df1

0   1   2   3   4
0      W   X   Y   Z
1  A  93  70  46  52
2  B   8  76  68  72
3  C   1  29  18  16
4  D  66  96  96  57
5  E  51  68  28  36

To get proper behavior, we can just reuse our original objects

In [12]:
df2 = pd.DataFrame(mytabular,myrowname,mycolname)
df2

W   X   Y   Z
A  93  70  46  52
B   8  76  68  72
C   1  29  18  16
D  66  96  96  57
E  51  68  28  36

___
## <font color=purple>Getting the shape of dataframes</font>

The shape method will return the row and column rank (count) of a dataframe.


In [13]:
df.shape

(5, 4)

In [14]:
df1.shape

(6, 5)

In [15]:
df2.shape

(5, 4)

___
## <font color=purple>Appending new columns</font>
To append a column simply assign a value to a new column name to the dataframe

In [16]:
df['new']= 'NA'
df

W   X   Y   Z new
A  18  36  59  93  NA
B  98  23  69  57  NA
C  11  29  28   7  NA
D  85  79  64  90  NA
E  29  24  69  20  NA

___
## <font color=purple>Appending new rows</font>
A bit trickier but we can create a copy of a row and concatenate it back into the dataframe.

In [17]:
newrow = df.loc[['E']].rename(index={"E": "X"}) # create a single row, rename the index
newtable = pd.concat([df,newrow]) # concatenate the row to bottom of df - note the syntax

In [18]:
newtable

W   X   Y   Z new
A  18  36  59  93  NA
B  98  23  69  57  NA
C  11  29  28   7  NA
D  85  79  64  90  NA
E  29  24  69  20  NA
X  29  24  69  20  NA

___
## <font color=purple>Removing Rows and Columns</font>

To remove a column is straightforward, we use the drop method

In [19]:
newtable.drop('new', axis=1, inplace = True)
newtable

W   X   Y   Z
A  18  36  59  93
B  98  23  69  57
C  11  29  28   7
D  85  79  64  90
E  29  24  69  20
X  29  24  69  20

To remove a row, you really got to want to, easiest is probablty to create a new dataframe with the row removed

In [20]:
newtable = newtable.loc[['A','B','D','E','X']] # select all rows except C
newtable

W   X   Y   Z
A  18  36  59  93
B  98  23  69  57
D  85  79  64  90
E  29  24  69  20
X  29  24  69  20

___
## <font color=purple>Indexing</font>
We have already been indexing, but a few examples follow:

In [21]:
newtable['X'] #Selecing a single column

A    36
B    23
D    79
E    24
X    24
Name: X, dtype: int64

In [22]:
newtable[['X','W']] #Selecing multiple columns

X   W
A  36  18
B  23  98
D  79  85
E  24  29
X  24  29

In [23]:
newtable.loc['E'] #Selecing rows based on label via loc[ ] indexer

W    29
X    24
Y    69
Z    20
Name: E, dtype: int64

In [24]:
newtable.loc[['E','X','B']] #Selecing multiple rows based on label via loc[ ] indexer

W   X   Y   Z
E  29  24  69  20
X  29  24  69  20
B  98  23  69  57

In [25]:
newtable.loc[['B','E','D'],['X','Y']] #Selecting elemens via both rows and columns via loc[ ] indexer

X   Y
B  23  69
E  24  69
D  79  64

___
## <font color=purple>Conditional Selection</font>


In [26]:
df = pd.DataFrame({'col1':[1,2,3,4,5,6,7,8],
                   'col2':[444,555,666,444,666,111,222,222],
                   'col3':['orange','apple','grape','mango','jackfruit','watermelon','banana','peach']})
df

col1  col2        col3
0     1   444      orange
1     2   555       apple
2     3   666       grape
3     4   444       mango
4     5   666   jackfruit
5     6   111  watermelon
6     7   222      banana
7     8   222       peach

In [27]:
#What fruit corresponds to the number 555 in ‘col2’?

df[df['col2']==555]['col3']

1    apple
Name: col3, dtype: object

In [28]:
#What fruit corresponds to the minimum number in ‘col2’?

df[df['col2']==df['col2'].min()]['col3']

5    watermelon
Name: col3, dtype: object

___
## <font color=purple>Descriptor Functions</font>

In [29]:
#Creating a dataframe from a dictionary

df = pd.DataFrame({'col1':[1,2,3,4,5,6,7,8],
                   'col2':[444,555,666,444,666,111,222,222],
                   'col3':['orange','apple','grape','mango','jackfruit','watermelon','banana','peach']})
df

col1  col2        col3
0     1   444      orange
1     2   555       apple
2     3   666       grape
3     4   444       mango
4     5   666   jackfruit
5     6   111  watermelon
6     7   222      banana
7     8   222       peach

### <font color=darkblue>`head` method</font>


Returns the first few rows, useful to infer structure

In [30]:
#Returns only the first five rows

df.head()

col1  col2       col3
0     1   444     orange
1     2   555      apple
2     3   666      grape
3     4   444      mango
4     5   666  jackfruit

### <font color=darkblue>`info` method</font>

Returns the data model (data column count, names, data types)

In [31]:
#Info about the dataframe

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    8 non-null      int64 
 1   col2    8 non-null      int64 
 2   col3    8 non-null      object
dtypes: int64(2), object(1)
memory usage: 320.0+ bytes


### <font color=darkblue>`describe` method</font>

Returns summary statistics of each numeric column.  
Also returns the minimum and maximum value in each column, and the IQR (Interquartile Range).  
Again useful to understand structure of the columns.

In [32]:
#Statistics of the dataframe

df.describe()

col1      col2
count  8.00000    8.0000
mean   4.50000  416.2500
std    2.44949  211.8576
min    1.00000  111.0000
25%    2.75000  222.0000
50%    4.50000  444.0000
75%    6.25000  582.7500
max    8.00000  666.0000

### <font color=darkblue>Counting and Sum methods</font>


There are also methods for counts and sums by specific columns

In [33]:
df['col2'].sum() #Sum of a specified column

3330

The `unique` method returns a list of unique values (filters out duplicates in the list, underlying dataframe is preserved)

In [34]:
df['col2'].unique() #Returns the list of unique values along the indexed column 

array([444, 555, 666, 111, 222])

The `nunique` method returns a count of unique values

In [35]:
df['col2'].nunique() #Returns the total number of unique values along the indexed column 

5

The `value_counts()` method returns the count of each unique value (kind of like a histogram, but each value is the bin)

In [36]:
df['col2'].value_counts()  #Returns the number of occurences of each unique value

222    2
444    2
666    2
111    1
555    1
Name: col2, dtype: int64

___
## <font color=purple>Using functions in dataframes - symbolic apply</font>

The power of pandas is an ability to apply a function to each element of a dataframe series (or a whole frame) by a technique called symbolic (or synthetic programming) application of the function.

Its pretty complicated but quite handy, best shown by an example

In [37]:
def times2(x):  # A prototype function to scalar multiply an object x by 2
    return(x*2)

print(df)
print('Apply the times2 function to col2')
df['col2'].apply(times2) #Symbolic apply the function to each element of column col2, result is another dataframe

   col1  col2        col3
0     1   444      orange
1     2   555       apple
2     3   666       grape
3     4   444       mango
4     5   666   jackfruit
5     6   111  watermelon
6     7   222      banana
7     8   222       peach
Apply the times2 function to col2


0     888
1    1110
2    1332
3     888
4    1332
5     222
6     444
7     444
Name: col2, dtype: int64

___
## <font color=purple>Sorts</font>
 

In [38]:
df.sort_values('col2', ascending = True) #Sorting based on columns 

col1  col2        col3
5     6   111  watermelon
6     7   222      banana
7     8   222       peach
0     1   444      orange
3     4   444       mango
1     2   555       apple
2     3   666       grape
4     5   666   jackfruit

___
## <font color=purple>Aggregating (Grouping Values) dataframe contents</font>


In [39]:
#Creating a dataframe from a dictionary

data = {
    'key' : ['A', 'B', 'C', 'A', 'B', 'C'],
    'data1' : [1, 2, 3, 4, 5, 6],
    'data2' : [10, 11, 12, 13, 14, 15],
    'data3' : [20, 21, 22, 13, 24, 25]
}

df1 = pd.DataFrame(data)
df1

key  data1  data2  data3
0   A      1     10     20
1   B      2     11     21
2   C      3     12     22
3   A      4     13     13
4   B      5     14     24
5   C      6     15     25

In [40]:
# Grouping and summing values in all the columns based on the column 'key'

df1.groupby('key').sum()

data1  data2  data3
key                     
A        5     23     33
B        7     25     45
C        9     27     47

In [41]:
# Grouping and summing values in the selected columns based on the column 'key'

df1.groupby('key')[['data1', 'data2']].sum()

data1  data2
key              
A        5     23
B        7     25
C        9     27

___
## <font color=purple>Filtering out missing values</font>

In [42]:
#Creating a dataframe from a dictionary

df = pd.DataFrame({'col1':[1,2,3,4,None,6,7,None],
                   'col2':[444,555,None,444,666,111,None,222],
                   'col3':['orange','apple','grape','mango','jackfruit','watermelon','banana','peach']})
df

col1   col2        col3
0   1.0  444.0      orange
1   2.0  555.0       apple
2   3.0    NaN       grape
3   4.0  444.0       mango
4   NaN  666.0   jackfruit
5   6.0  111.0  watermelon
6   7.0    NaN      banana
7   NaN  222.0       peach

Below we drop any row that contains a `NaN` code.

In [43]:
df_dropped = df.dropna()
df_dropped

col1   col2        col3
0   1.0  444.0      orange
1   2.0  555.0       apple
3   4.0  444.0       mango
5   6.0  111.0  watermelon

Below we replace `NaN` codes with some value, in this case 0

In [44]:
df_filled1 = df.fillna(0)
df_filled1

col1   col2        col3
0   1.0  444.0      orange
1   2.0  555.0       apple
2   3.0    0.0       grape
3   4.0  444.0       mango
4   0.0  666.0   jackfruit
5   6.0  111.0  watermelon
6   7.0    0.0      banana
7   0.0  222.0       peach

Below we replace `NaN` codes with some value, in this case the mean value of of the column in which the missing value code resides.

In [45]:
df_filled2 = df.fillna(df.mean())
df_filled2

col1   col2        col3
0  1.000000  444.0      orange
1  2.000000  555.0       apple
2  3.000000  407.0       grape
3  4.000000  444.0       mango
4  3.833333  666.0   jackfruit
5  6.000000  111.0  watermelon
6  7.000000  407.0      banana
7  3.833333  222.0       peach

___
## <font color=purple>Reading a File into a Dataframe</font>

Pandas has methods to read common file types, such as `csv`,`xlsx`, and `json`.  Ordinary text files are also quite manageable.

On a machine you control you can write script to retrieve files from the internet and process them.


In [46]:
import pandas as pd 
readfilecsv = pd.read_csv('CSV_ReadingFile.csv')  #Reading a .csv file
print(readfilecsv)

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15


Similar to reading and writing .csv files, you can also read and write .xslx files as below (useful to know this)

In [47]:
readfileexcel = pd.read_excel('Excel_ReadingFile.xlsx', sheet_name='Sheet1', engine='openpyxl') #Reading a .xlsx file
print(readfileexcel)

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15


___
## <font color=purple>Writing a dataframe to file</font>

In [48]:
#Creating and writing to a .csv file
readfilecsv = pd.read_csv('CSV_ReadingFile.csv')
readfilecsv.to_csv('CSV_WritingFile1.csv')
readfilecsv = pd.read_csv('CSV_WritingFile1.csv')
print(readfilecsv)

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15


In [49]:
#Creating and writing to a .csv file by excluding row labels 
readfilecsv = pd.read_csv('CSV_ReadingFile.csv')
readfilecsv.to_csv('CSV_WritingFile2.csv', index = False)
readfilecsv = pd.read_csv('CSV_WritingFile2.csv')
print(readfilecsv)

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15


In [50]:
#Creating and writing to a .xlsx file
readfileexcel = pd.read_excel('Excel_ReadingFile.xlsx', sheet_name='Sheet1', index = False)
readfileexcel.to_excel('Excel_WritingFile.xlsx', sheet_name='MySheet', index = False)
readfileexcel = pd.read_excel('Excel_WritingFile.xlsx', sheet_name='MySheet', index = False)
print(readfileexcel)

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15


___
## <font color=orange>This is a Pandas Cheat Sheet</font>

![](https://i.pinimg.com/originals/39/08/5c/39085c27945ad3eb49e0de7dff6f0b0e.png)


___
![](https://media2.giphy.com/media/5nj4ZZWl6QwneEaBX4/source.gif) <br>

*Here are some of the resources used for creating this notebook:* 

- Pandas foundations. Retrieved February 15, 2021, from https://www.datacamp.com/courses/pandas-foundations <br>
- Pandas tutorial. Retrieved February 15, 2021, from https://www.w3schools.com/python/pandas/default.asp <br>
- Pandas tutorial: Dataframes in Python. Retrieved February 15, 2021, from https://www.datacamp.com/community/tutorials/pandas-tutorial-dataframe-python <br>

*Here are some great reads on this topic:* 
- __"Introduction to Pandas in Python"__ available at *https://www.geeksforgeeks.org/introduction-to-pandas-in-python/<br>
- __"Pandas Introduction & Tutorials for Beginners"__ by __Walker Rowe__, available at *https://www.bmc.com/blogs/pandas-basics/ <br>
- __"Using Pandas and Python to Explore Your Dataset"__ by __Reka Horvath__ available at *https://realpython.com/pandas-python-explore-dataset/ <br>
- __"Python Pandas Tutorial: A Complete Introduction for Beginners"__ by __George McIntire, Lauren Washington, and Brendan Martin__ available at *https://www.learndatasci.com/tutorials/python-pandas-tutorial-complete-introduction-for-beginners/ <br>


*Here are some great videos on these topics:* 
- __"Python: Pandas Tutorial | Intro to DataFrames"__ by __Joe James__ available at *https://www.youtube.com/watch?v=e60ItwlZTKM <br>
- __"Complete Python Pandas Data Science Tutorial! (Reading CSV/Excel files, Sorting, Filtering, Groupby)"__ by __Keith Galli__ available at *https://www.youtube.com/watch?v=vmEHCJofslg <br>
- __"What is Pandas? Why and How to Use Pandas in Python"__ by __Python Programmer__ available at *https://www.youtube.com/watch?v=dcqPhpY7tWk <br>


___
![](https://media2.giphy.com/media/dNgK7Ws7y176U/200.gif) <br>


## Exercise: Pandas of Data  <br>

### Pandas library supports three major types of data structures: Series, DataFrames, and Panels. What are some differences between the three structures?

#### * Make sure to cite any resources that you may use. 

![](https://www.quotemaster.org/images/q/13084/1308445/i4.png)
![](https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/bad-panda-balazs-solti.jpg)