In [47]:
import numpy as np         #import numpy
Array1 = np.array([0,12,24,36,48,60,72,84,96])     #Step1: Define Array1
print(Array1)

[ 0 12 24 36 48 60 72 84 96]


In [48]:
print(Array1*2.0)

[  0.  24.  48.  72.  96. 120. 144. 168. 192.]


In [49]:
print(Array1**2) 

[   0  144  576 1296 2304 3600 5184 7056 9216]


In [50]:
print(np.power(Array1,2)) 

[   0  144  576 1296 2304 3600 5184 7056 9216]


In [53]:
print(np.min(Array1)) 

0


In [54]:
print(np.argmin(Array1)) 

0


In [55]:
Array2 = np.array([-12,0,12,24,36,48,60,72,84])     #Step6: Define Array2
print(Array2)

[-12   0  12  24  36  48  60  72  84]


In [56]:
print(Array1+Array2) 

[-12  12  36  60  84 108 132 156 180]


In [57]:
print(Array1-Array2) 

[12 12 12 12 12 12 12 12 12]


In [58]:
print(Array1*Array2)  

[   0    0  288  864 1728 2880 4320 6048 8064]


In [59]:


import numpy as np         #import numpy
Array1 = np.array([[5,10],[15,20]])     #Step1: Define Array1
print(Array1)



[[ 5 10]
 [15 20]]


In [60]:
Array2 = np.array([[3,6],[9,12]])     #Step2: Define Array2
print(Array2)

[[ 3  6]
 [ 9 12]]


In [62]:
print(Array1-Array2) 

[[2 4]
 [6 8]]


In [63]:
MultArray = Array1@Array2 
print(MultArray)

[[105 150]
 [225 330]]


In [64]:
MultArray1 = Array1.dot(Array2) 
print(MultArray1)

[[105 150]
 [225 330]]


In [65]:
print(np.argmax(MultArray)) 

3


In [67]:
print(np.mean(MultArray))     ##Step6: Find the mean of the multiplication of these two arrays 
print(np.mean(MultArray[:,:]))


202.5
202.5


In [68]:
import numpy as np         #import numpy
Array1 = np.array([1.0,2.5,3.4,7,7])     #Step1: Define Array1
print(Array1)
Array2 = np.array([5.0/5.0,5.0/2,6.8/2,21/3,14/2])     #Step2: Define Array1
print(Array2)
print(np.equal(Array1, Array2))             #Step3: Compare and see if the two arrays are equal
Array3 = np.array([6,1.4,2.2,7.5,7])     #Step4: Define Array3
print(Array3)
print(np.greater_equal(Array1, Array3))             #Step3: Compare and see if the two arrays are equal

[1.  2.5 3.4 7.  7. ]
[1.  2.5 3.4 7.  7. ]
[ True  True  True  True  True]
[6.  1.4 2.2 7.5 7. ]
[False  True  True False  True]


In [69]:
import numpy as np         #import numpy
Array1 = np.array([[4,40],[68,72]])     #Step1: Define Array1
print(Array1)
Array2 = np.array([[9,23],[39,55]])     #Step2: Define Array2
print(Array2)
print(np.less_equal(Array1,Array2))

[[ 4 40]
 [68 72]]
[[ 9 23]
 [39 55]]
[[ True False]
 [False False]]


In [70]:
import numpy as np         #import numpy
x = np.array([1,2,3])     #Step1: Define x
print(x)

[1 2 3]


In [71]:
y = x                     #Step2: Assign y as y=x
print(y)

[1 2 3]


In [72]:
z = np.copy(x)    #Step3: Define z as a copy of x
print(z)

[1 2 3]


In [73]:
print('x = ',x)  # They look similar but ...
print('y = ',y)
print('z = ',z)

x =  [1 2 3]
y =  [1 2 3]
z =  [1 2 3]


In [74]:
x[1]=200

In [75]:
print('x = ',x)  # They look similar but ...
print('y = ',y)
print('z = ',z)

x =  [  1 200   3]
y =  [  1 200   3]
z =  [1 2 3]


In [76]:
print(' x object at hex address ',hex(id(x)))
print(' y object at hex address ',hex(id(y)))
print(' z object at hex address ',hex(id(z)))

 x object at hex address  0xffff980dd8f0
 y object at hex address  0xffff980dd8f0
 z object at hex address  0xffff9813a620


In [77]:
x = np.delete(x, 1)      #Step5: Delete the second element of x, remember counting starts at zero
print('x = ',x)  # For Step4: They look similar but ...
print('y = ',y)
print('z = ',z)


x =  [1 3]
y =  [  1 200   3]
z =  [1 2 3]


In [78]:
print(' x object at hex address ',hex(id(x))) # lets check the objects - now they are all different
print(' y object at hex address ',hex(id(y)))
print(' z object at hex address ',hex(id(z)))

 x object at hex address  0xffff980e48f0
 y object at hex address  0xffff980dd8f0
 z object at hex address  0xffff9813a620


In [79]:
import numpy as np         #import numpy
games = np.array(['FIFA 2020','Red Dead Redemption','Fallout','GTA','NBA 2018','Need For Speed'])
print(games)
print(np.sort(games))

['FIFA 2020' 'Red Dead Redemption' 'Fallout' 'GTA' 'NBA 2018'
 'Need For Speed']
['FIFA 2020' 'Fallout' 'GTA' 'NBA 2018' 'Need For Speed'
 'Red Dead Redemption']


In [80]:
import numpy as np         #import numpy
a = np.array([[17,-6,2],[86,-12,0],[0,23,12]])
print(a)
print ("Along columns : \n", np.sort(a,axis = 0) ) #This will be sorting in each column
print ("Along rows : \n", np.sort(a,axis = 1) ) #This will be sorting in each row
print ("Sorting by default : \n", np.sort(a) )          #Same as above
print ("Along None Axis : \n", np.sort(a,axis = None) ) #This will be sorted like a 1D array

[[ 17  -6   2]
 [ 86 -12   0]
 [  0  23  12]]
Along columns : 
 [[  0 -12   0]
 [ 17  -6   2]
 [ 86  23  12]]
Along rows : 
 [[ -6   2  17]
 [-12   0  86]
 [  0  12  23]]
Sorting by default : 
 [[ -6   2  17]
 [-12   0  86]
 [  0  12  23]]
Along None Axis : 
 [-12  -6   0   0   2  12  17  23  86]


In [81]:
import numpy as np         #import numpy
a = np.array([1,3,5,7,9])     #Define the array
print(a)
aslice = a[1:4]             #slice the [3,5,7]
print(aslice) 

[1 3 5 7 9]
[3 5 7]
